Add Qdrant Service and Speaker Identification Configuration
linto-ai/linto pull request #1
Opened 2024-11-05 16:17 UTC by htagourti

1. Integrated Qdrant service into the stack
2. Added dialog option to enable/disable speaker identification
3. Updated diarization config with Qdrant variables

2024-11-06 14:34 UTC, damienlaine requested changes
See @Houpert comments.
Pending approval

2024-11-07 08:30 UTC, htagourti commented on services/stt/diarization-pyannote/template.jsonnet
> +        #shared_mount + '/audios/speaker_samples:/opt/speaker_samples', # Reference speakers samples
The idea was to allow the user not to deploy qdrant if they don't want speaker identification (without having to edit the service files). Including qdrant in the diarization config means the user would have to manually change the files to enable / disable the service.

2024-11-07 09:03 UTC, Houpert commented on services/stt/diarization-pyannote/template.jsonnet
> +        #shared_mount + '/audios/speaker_samples:/opt/speaker_samples', # Reference speakers samples
That’s why I suggested creating two separate configurations: one with only `diarization-pyannote` (based on the setup prior to your PR) and a new `diarization-pyannote-qdrant` configuration that includes both services in the same YAML file. Then, depending on the user's desired setup, you can select the version to build with or without Qdrant.

2024-11-08 11:57 UTC, htagourti commented on scripts/dialog.sh
> +    # Initialize speaker identification variable
Done.
Created `dialog_speaker_identification` and updated `setup-service.sh` : 
```
if [[ "$services" =~ (^|[[:space:]])3($|[[:space:]]) && "$services" =~ (^|[[:space:]])(1|2)($|[[:space:]]) ]]; then
    speaker_identification=$(./scripts/dialog.sh "speaker_identification")
    
    if [[ "$speaker_identification" == "true" ]]; then
        diarization_enable="stt-diarization-pyannote-qdrant"
    else
        diarization_enable="stt-diarization-pyannote"
    fi
fi

```

2024-11-08 12:05 UTC, htagourti commented on scripts/build-services.sh
> +        generate_yaml_files "services/stt/diarization-pyannote" false false $1
Created 2 seperate services depending on user choice for speaker id : 

- diarization-pyannote-qdrant
- diarization-pyannote

2024-11-08 13:06 UTC, Houpert commented on scripts/build-services.sh
> +        generate_yaml_files "services/stt/diarization-pyannote" false false $1
Please remember to remove the `qdrant-vector-db` service. Since it's now integrated with the `diarization-pyannote-qdrant` service, keeping it separately is redundant."

2024-11-08 13:15 UTC, Houpert commented on scripts/setup-services.sh
> +    echo $service
You can remove that echo, it's show us just number

2024-11-08 13:27 UTC, merged